### ISSUE TITLE
Edit Suggestion: Making Decisions With Conditionals

### ISSUE THREAD

**Issue by Habenzy** [BurlingtonCodeAcademy/webdev-prework-track#7]
Add a sentence after line 48 explaining that those values `true` or `false` that you get back are what's known as "booleans." There's a good description of what we get back, and why it's that value, but we've never given them a name for the data type, and it might be construed as the string "true" or "false" rather than a separate data type.

**Comment by pphelps28** [comment]
I added a few sentences to the end of the paragraph on line 48 that does as Habenzy has suggested; I mention that `true` and `false` are reserved words in JavaScript, and are the result of comparing two values.
